<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QaBoxVM02" failures="2" tests="2" name="Default test" time="17.262" errors="0" timestamp="2025-03-18T11:44:15 UTC">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.63">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at StepDefination.CheckoutPageSD.User_proceed_to_checkout_and_verify_the_name_in_page(CheckoutPageSD.java:33)
at ✽.User proceed to the checkout page and verify the Beet in the page(file:///C:/Users/Nayan/Documents/Eclipse-Workspace/CucumberActualFramework/src/test/java/feature/Checkout.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="15.716">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at StepDefination.CheckoutPageSD.User_proceed_to_checkout_and_verify_the_name_in_page(CheckoutPageSD.java:33)
at ✽.User proceed to the checkout page and verify the Tom in the page(file:///C:/Users/Nayan/Documents/Eclipse-Workspace/CucumberActualFramework/src/test/java/feature/Checkout.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
